/**
 * Build script for Vercel deployment.
 * Generates config.js from environment variables so that
 * credentials stay out of version control.
 */
const fs = require('fs');

const clientId = process.env.GOOGLE_CLIENT_ID;
const apiKey = process.env.GOOGLE_API_KEY;

if (!clientId || !apiKey) {
    console.error('ERROR: Missing required environment variables.');
    console.error('  - GOOGLE_CLIENT_ID');
    console.error('  - GOOGLE_API_KEY');
    console.error('Set these in your Vercel project settings under Environment Variables.');
    process.exit(1);
}

const configContent = `// Auto-generated by build.js — do not edit manually.
const CLIENT_ID = '${clientId}';
const API_KEY = '${apiKey}';
`;

fs.writeFileSync('config.js', configContent);
console.log('✓ config.js generated successfully.');
